### ISSUE TITLE
Success With Version 1

### ISSUE THREAD

**Issue by war59312** [aguinet/wannakey#1]
Hi,

Looks good. Success.. :)

Note: First time, got the msvcp120.dll not found error.

Should note that you need Visual C++ Redistributable Packages for Visual Studio 2013 (https://www.microsoft.com/en-us/download/details.aspx?id=40784) for this to work.

FYI THIS DOES NOT WORK HOWEVER WITH Version 2: 

> ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa

Sample from:

> hxxps://www.hybrid-analysis.com/sample/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa?environmentId=100

As no `wcry.exe` process.

Thanks,

Will

**Comment by pikami** [comment]
@war59312 I tried it with the "ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa" version and used the PID of the process "ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa.exe" after a few minutes it got the key, but when I try to decrypt a file with wanafork it returns:
`[ CryptImportKey : Bad Key.`

**Comment by aguinet** [comment]
Hello! That's an issue I got to fix. Apparently the key format I generate does not work under Windows XP. In the meantine, you can thought use wannafork under Win10 with the key file wannakey produces and a copy of your encrypted files!

You can also look at https://github.com/gentilkiwi/wanakiwi which reimplemented the whole thing using OpenSSL!

**Comment by aguinet** [comment]
What I said above should be fixed now.

**Comment by war59312** [comment]
@aguinet TY! 🥇

@pikami Indeed. Thanks. I realize now I just left the room for a bit and when I came back the exe had already closed.
