### ISSUE TITLE
Why do the miller_rabin_test() at all?

### ISSUE THREAD

**Issue by tavianator** [aguinet/wannakey#2]
It should be sufficient, and much faster, to just check `if (P > 1 && N % P == 0)` right?

**Comment by leonklingele** [comment]
👍 but you need to check for `P != N` as well.

**Comment by leonklingele** [comment]
Throwing out `normalizedEntropy` will then make it even faster.

**Comment by aguinet** [comment]
That's stuff that are there because I was checking this step by step. I haven't done yet an optimization pass phase, so you might be right, but real-life benchmarks will tell! (need to do them!)

**Comment by tavianator** [comment]
@leonklingele

> but you need to check for `P != N` as well.

 In general yeah.  But if P is always 1024 bits and N is always 2048 bits then you don't need to :)

**Comment by aguinet** [comment]
So I did some benchmark and you're right, the miller rabin test was really slowing down the whole thing. Fixed code and benchmarking code has just been pushed!
