### ISSUE TITLE
why win7 donot used？

### ISSUE THREAD

**Issue by yale8848** [aguinet/wannakey#4]
why win7 donot used？

**Comment by stamepicmorg** [comment]
for   Windows 7 x86, 2003, Vista, Server 2008 и 2008 R2 + you can use this tool:

https://github.com/gentilkiwi/wanakiwi

Windows XP supported too

**Comment by aguinet** [comment]
Acutally this tool also works with the other versions. The idea is copied..

I'll update this page and tool tomorrow!

**Comment by yale8848** [comment]
ok,thanks!
