### ISSUE TITLE
How wannakey works?

### ISSUE THREAD

**Issue by queston02** [aguinet/wannakey#6]
Want to know how one process i.e. wannakey.exe is able to access the memory of another process i.e. wcry.exe. Isn't accessing another process memory restricted in windows?

**Comment by bothie** [comment]
a) Accessing memory is restricted.
b) Debuggers need a way to access other processes memory anyways.

Consequently, almost[1] all operating systems support some kind of debug interface. Windows implements this using the OpenProcess API, Linux via ptrace (short for process trace), other systems have their own interfaces. Of course, the calling process needs the access rights to the victim process.

[1] I don't know of any exceptions, but probably there is one I don't know, so I say almost ;)
