### ISSUE TITLE
leakage on Windows 10 found by winapi_check was false alarm?

### ISSUE THREAD

**Issue by JohnnyLChang** [aguinet/wannakey#9]
I checked the memory address that reported by winapi_check. It was created by vector in process.cpp for comparison. When winapi_check use it to check the address will be always different, that's why Windows 10 also report leakage.

After I modify the code by checking the MemInfo.BaseAddress, it will not report leakage.

P: 00BAEAB0
Q: 00BAEA28
Key generated, zeroying data at 00baeb60...
Will destroy key...
Will release ctx...
MemInfo.BaseAddress009B0000
MemInfo.BaseAddress00A20000
MemInfo.BaseAddress00AA8000
MemInfo.BaseAddress00BAC000
Found P at 00BAEAB0 => I changed to memory block address with offset
Found P at heap 026E2310 => this was created by std::vector<uint8_t> Buf; @process.cpp #138
Found Q at 00BAEA28
Found Q at heap 026E2288

**Comment by aguinet** [comment]
I think ti was indeed false alarm. I fixed this on the new version just pushed!

**Comment by aguinet** [comment]
A really nicer way to do this would be to spawn two processes, with one that checks the other.. !

**Comment by JohnnyLChang** [comment]
agree!
